language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
env:
  - BOOST_BRANCH=boost-1.58.0
before_script:
  #- sudo apt-get update -qq -y
  #- sudo apt-get install libboost1.58-dev -y
  # From this point and below code is same for all the Boost libs
  # Cloning Boost libraries (fast nondeep cloning)
  - PROJECT_DIR=`pwd`
  - git --version
  - BOOST=$HOME/boost
  - git clone -b $BOOST_BRANCH https://github.com/boostorg/boost.git $BOOST
  - cd $BOOST
  - git submodule update --init --merge
  - ./bootstrap.sh
  - ./b2 headers
  - cd $PROJECT_DIR
  - mkdir build-zz
  - cd build-zz
  - cmake ../thrash
  - make
after_success:
  - ./Example-Person
