language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update -qq -y
  - sudo apt-get install libboost1.58-dev -y
script:
  - mkdir build-zz
  - cd build-zz
  - cmake ../thrash
  - make
after_success:
  - ./Example-Person
