#https://docs.travis-ci.com/user/customizing-the-build/
#compilers in Travis: https://jonasw.de/blog/2015/07/22/develop/cplusplus14-on-travis-with-cmake/
#also: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
#Coverity: https://scan.coverity.com/travis_ci
# script: 

language: cpp
sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "gHPBb6h78cvF5nQ1sH8mv7C8ZDHmZNHF0CIwfmAlYVqT/MHcG0v+whz2X82bvmwceLA5qMrP8okq1MmO4cP1H3dVd53u7r9gx1SXvXJ96CnjGwOshVCZQ04dIqVJb0UIU4RpJ9dIMiC2TtstDkB2BQufQjuZtW+R3BpbyHzpIHgX7FVG549mdjFbqQQCov3cjvgNGM1Luh3Jn0WFQQqzshyRR+fnuKYAEm7TI+DA5+PtrF2X0Z3R1BQXhZ0W3XQKwzFQGOSLSMTP6LVPWpSNrVWp7KViAeLUM26KNL8333reptBhFsQNmjzV4a7fdlTRpT/7Zvu4mKRXj5VtDQ6vH051YWvrnbdn8ctSg+oO9zKMQnhlwEYk5FppunHE2mqqOEATHdD6c8irf2JMFU4NMJ6CUuex8+De/spsvsIYkC7bb8zcFYfmmeOa1xfu5vKb/E8U9kH0LKSwQ5eD0XJM9WMAoDbIxp2OjPpcc8/13GYNUSIpB/giWyUztSspclm2ckaQDIjHM+t8wLnOz8PUoU8ufxpb4Lg7f1wWogtCptk4FXRHz7qQkQ2ApPVa26xOKnVeJQI4otMWLUrMbeKlCaEuhTUY1EAxf9gbVjB/Rf7ezpeG/Wz5ET5cjgytvP2TlgciXTtlFk9zeVV3Kuu0OSxBd4A7mDTEHXeonAVxP9E="

addons:
  coverity_scan:
    project:
      name: "Zbyl/ArbitraryFormatSerializer"
      description: "Build submitted via Travis CI"
    notification_email: zbychs@gmail.com
    build_command_prepend: "./ci-builds/prepare-build.sh; cd build-zz"
    build_command:   "if [ ${COMPILER} == g++-5 ]; then make; else exit 1; fi"
    branch_pattern: coverity_scan

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - COMPILER=g++-4.9
        - BOOST_VER=57
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5
        - BOOST_VER=58
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - COMPILER=clang++-3.7
        - BOOST_VER=58
        - BOOST_TOOLSET=clang

before_install:
  #- pip install --user cpp-coveralls

before_script:
  - . ./ci-builds/download-boost.sh $BOOST_VER

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./ci-builds/build.sh ; fi

after_success:
  #- coveralls --exclude lib --exclude tests --gcov-options '\-lp'
